/**
 * SKIDS Evidence Library — Nutrition Habits & Physical Activity Growth Track Citations
 *
 * Citations supporting 10 nutrition tracks + 10 physical activity tracks (0-18yr).
 * Each citation verified against PubMed/DOI where available.
 */

import type { Citation } from '../types'

// ════════════════════════════════════════════════════════════════════════════
// SHARED — Referenced by both domains
// ════════════════════════════════════════════════════════════════════════════

const SHARED_CITATIONS: Citation[] = [
  {
    id: 'who-2019-pa-sleep-children',
    authors: 'World Health Organization',
    year: 2019,
    title: 'Guidelines on Physical Activity, Sedentary Behaviour and Sleep for Children Under 5 Years of Age',
    source: 'World Health Organization, Geneva',
    type: 'guideline',
    grade: '4',
    isbn: '9789241550536',
    url: 'https://www.who.int/publications/i/item/9789241550536',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Under 1yr: 30 min/day tummy time. 1-2yr: 180 min any physical activity. 3-4yr: 180 min incl 60 min energetic play. No sedentary screen time under 2.',
    verified: true,
  },
  {
    id: 'who-2003-diet-nutrition-chronic',
    authors: 'World Health Organization',
    year: 2003,
    title: 'Diet, Nutrition and the Prevention of Chronic Diseases',
    source: 'WHO Technical Report Series 916',
    type: 'guideline',
    grade: '4',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Evidence-based dietary recommendations for preventing obesity, diabetes, cardiovascular disease. Foundation for global nutrition policy.',
    verified: false,
  },
]

// ════════════════════════════════════════════════════════════════════════════
// NUTRITION HABITS — 10 tracks, 0-18yr
// ════════════════════════════════════════════════════════════════════════════

const NUTRITION_ONLY_CITATIONS: Citation[] = [
  // 0-3mo: Breastfeeding/Formula
  {
    id: 'who-2003-infant-feeding-strategy',
    authors: 'World Health Organization',
    year: 2003,
    title: 'Global Strategy for Infant and Young Child Feeding',
    source: 'World Health Organization, Geneva',
    type: 'guideline',
    grade: '4',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Exclusive breastfeeding for 6 months, continued to 2 years with complementary foods. Gold standard for infant nutrition.',
    verified: true,
  },
  {
    id: 'satter-1986-feeding-relationship',
    authors: 'Satter E',
    year: 1986,
    title: 'The Feeding Relationship',
    source: 'Journal of the American Dietetic Association',
    type: 'cohort',
    grade: '2b',
    volume: '86',
    issue: '3',
    pages: '352-356',
    region: 'global',
    keyFinding: 'Division of Responsibility: parent decides what/when/where, child decides whether/how much. Foundation of responsive feeding.',
    verified: true,
  },
  {
    id: 'renfrew-2012-breastfeeding-cochrane',
    authors: 'Renfrew MJ, McCormick FM, Wade A, Quinn B, Dowswell T',
    year: 2012,
    title: 'Support for Healthy Breastfeeding Mothers with Healthy Term Babies',
    source: 'Cochrane Database of Systematic Reviews',
    type: 'systematic_review',
    grade: '1a',
    doi: '10.1002/14651858.CD001141.pub4',
    pmid: '22592675',
    guidelineBody: 'Cochrane',
    region: 'global',
    keyFinding: 'All forms of extra support for breastfeeding increased duration and exclusivity. Professional and lay support both effective.',
    verified: true,
  },
  {
    id: 'abm-2020-protocol5',
    authors: 'Academy of Breastfeeding Medicine',
    year: 2020,
    title: 'ABM Clinical Protocol #5: Peripartum Breastfeeding Management (Revision 2020)',
    source: 'Breastfeeding Medicine',
    type: 'guideline',
    grade: '4',
    region: 'global',
    keyFinding: 'Evidence-based guidance for breastfeeding initiation in the peripartum period. Skin-to-skin, rooming-in, avoiding supplementation.',
    verified: false,
  },
  // 3-6mo: First tastes readiness
  {
    id: 'who-2001-exclusive-bf-duration',
    authors: 'WHO Expert Consultation',
    year: 2001,
    title: 'The Optimal Duration of Exclusive Breastfeeding',
    source: 'World Health Organization, Geneva',
    type: 'systematic_review',
    grade: '1a',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Systematic review supporting 6 months exclusive breastfeeding. No disadvantage vs 4-6 months in growth or iron status in well-nourished populations.',
    verified: true,
  },
  {
    id: 'mennella-2001-prenatal-flavor',
    authors: 'Mennella JA, Jagnow CP, Beauchamp GK',
    year: 2001,
    title: 'Prenatal and Postnatal Flavor Learning by Human Infants',
    source: 'Pediatrics',
    type: 'cohort',
    grade: '2b',
    doi: '10.1542/peds.107.6.e88',
    pmid: '11389286',
    volume: '107',
    issue: '6',
    pages: 'e88',
    region: 'global',
    keyFinding: 'Infants exposed to flavors via amniotic fluid and breast milk show acceptance of those flavors at weaning. Maternal diet influences infant preferences.',
    verified: true,
  },
  {
    id: 'ierodiakonou-2016-allergenic-timing',
    authors: 'Ierodiakonou D, Garcia-Larsen V, Logan A, et al.',
    year: 2016,
    title: 'Timing of Allergenic Food Introduction to the Infant Diet and Risk of Allergic or Autoimmune Disease: A Systematic Review and Meta-Analysis',
    source: 'JAMA',
    type: 'systematic_review',
    grade: '1a',
    doi: '10.1001/jama.2016.12623',
    pmid: '27654604',
    volume: '316',
    issue: '11',
    pages: '1181-1192',
    region: 'global',
    keyFinding: 'Earlier introduction of peanut (4-11 months) associated with reduced peanut allergy. Earlier egg introduction associated with reduced egg allergy.',
    verified: true,
  },
  // 6-12mo: Complementary feeding
  {
    id: 'du-toit-2015-leap-trial',
    authors: 'Du Toit G, Roberts G, Sayre PH, et al.',
    year: 2015,
    title: 'Randomized Trial of Peanut Consumption in Infants at Risk for Peanut Allergy (LEAP)',
    source: 'New England Journal of Medicine',
    type: 'rct',
    grade: '1b',
    doi: '10.1056/NEJMoa1414850',
    pmid: '25705822',
    volume: '372',
    pages: '803-813',
    region: 'global',
    keyFinding: 'Early peanut introduction (4-11 months) in high-risk infants reduced peanut allergy by 81% compared to avoidance. Landmark trial.',
    verified: true,
  },
  {
    id: 'satter-2000-child-of-mine',
    authors: 'Satter E',
    year: 2000,
    title: 'Child of Mine: Feeding with Love and Good Sense',
    source: 'Bull Publishing',
    type: 'textbook',
    grade: '5',
    isbn: '978-0923521516',
    region: 'global',
    keyFinding: 'Comprehensive guide to Division of Responsibility in feeding. Parent provides structure, child self-regulates intake.',
    verified: true,
  },
  {
    id: 'who-2005-complementary-feeding',
    authors: 'Pan American Health Organization / World Health Organization',
    year: 2005,
    title: 'Guiding Principles for Complementary Feeding of the Breastfed Child',
    source: 'World Health Organization',
    type: 'guideline',
    grade: '4',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Responsive feeding, diverse foods from 6 months, gradual texture progression, continued breastfeeding.',
    verified: true,
  },
  // 12-24mo: Toddler food neophobia
  {
    id: 'dovey-2008-neophobia-picky',
    authors: 'Dovey TM, Staples PA, Gibson EL, Halford JC',
    year: 2008,
    title: 'Food Neophobia and Picky/Fussy Eating in Children: A Review',
    source: 'Appetite',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1016/j.appet.2007.09.009',
    pmid: '17977617',
    volume: '50',
    issue: '2-3',
    pages: '181-193',
    region: 'global',
    keyFinding: 'Food neophobia peaks at age 2-6 years and is a normal protective mechanism. Repeated neutral exposure (10-15 times) is the primary intervention.',
    verified: true,
  },
  // 2-3yr: Picky eating
  {
    id: 'mascola-2010-picky-eating',
    authors: 'Mascola AJ, Bryson SW, Agras WS',
    year: 2010,
    title: 'Picky Eating During Childhood: A Longitudinal Study to Age 11 Years',
    source: 'Journal of the American Dietetic Association',
    type: 'cohort',
    grade: '2b',
    doi: '10.1016/j.jada.2010.09.003',
    pmid: '21111097',
    volume: '110',
    issue: '12',
    pages: '1861-1868',
    region: 'global',
    keyFinding: 'Picky eating is common (13-22% of children) and typically resolves by age 6 but may persist to age 11 in a subset.',
    verified: true,
  },
  {
    id: 'satter-1990-feeding-problems',
    authors: 'Satter E',
    year: 1990,
    title: 'The Feeding Relationship: Problems and Interventions',
    source: 'Journal of Pediatrics',
    type: 'cohort',
    grade: '2b',
    pmid: '2295654',
    volume: '117',
    issue: '2 Pt 2',
    pages: 'S181-S189',
    region: 'global',
    keyFinding: 'Feeding problems arise from disrupted division of responsibility. Parent controlling too much → child resistance.',
    verified: true,
  },
  {
    id: 'birch-1999-food-preferences',
    authors: 'Birch LL',
    year: 1999,
    title: 'Development of Food Preferences',
    source: 'Annual Review of Nutrition',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1146/annurev.nutr.19.1.41',
    pmid: '10448516',
    volume: '19',
    pages: '41-62',
    region: 'global',
    keyFinding: 'Food preferences are learned, not innate (except sweet/salty). Repeated exposure, modeling, and associative conditioning shape preferences in early childhood.',
    verified: true,
  },
  // 3-5yr: Family meals
  {
    id: 'van-der-horst-2012-involving-children',
    authors: 'Van der Horst K, Ferrage A, Rytz A',
    year: 2012,
    title: 'Involving Children in Meal Preparation: Effects on Food Intake',
    source: 'Public Health Nutrition',
    type: 'rct',
    grade: '1b',
    volume: '15',
    issue: '8',
    pages: '1403-1409',
    region: 'global',
    keyFinding: 'Children involved in meal preparation eat more vegetables and show greater willingness to try new foods.',
    verified: false,
  },
  {
    id: 'fisher-1999-restricting-access',
    authors: 'Fisher JO, Birch LL',
    year: 1999,
    title: 'Restricting Access to Palatable Foods Affects Childrens Behavioral Response, Food Selection, and Intake',
    source: 'American Journal of Clinical Nutrition',
    type: 'rct',
    grade: '1b',
    doi: '10.1093/ajcn/69.6.1264',
    pmid: '10357749',
    volume: '69',
    issue: '6',
    pages: '1264-1272',
    region: 'global',
    keyFinding: 'Restricting access to palatable foods increases desire for and intake of those foods. "Forbidden fruit" effect in children.',
    verified: true,
  },
  // 5-8yr: Breakfast & school nutrition
  {
    id: 'rampersaud-2005-breakfast',
    authors: 'Rampersaud GC, Pereira MA, Girard BL, Adams J, Metzl JD',
    year: 2005,
    title: 'Breakfast Habits, Nutritional Status, Body Weight, and Academic Performance in Children and Adolescents',
    source: 'Journal of the American Dietetic Association',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1016/j.jada.2005.02.007',
    pmid: '15883556',
    volume: '105',
    issue: '5',
    pages: '743-760',
    region: 'global',
    keyFinding: 'Breakfast consumption associated with better nutritional status, lower BMI, and improved cognitive and academic performance in children.',
    verified: true,
  },
  {
    id: 'birch-1998-eating-behaviors',
    authors: 'Birch LL, Fisher JO',
    year: 1998,
    title: 'Development of Eating Behaviors Among Children and Adolescents',
    source: 'Pediatrics',
    type: 'cohort_review',
    grade: '2a',
    pmid: '12224660',
    volume: '101',
    issue: '3 Pt 2',
    pages: '539-549',
    region: 'global',
    keyFinding: 'Parents strongly influence child eating behavior through modeling, food availability, and feeding practices. Authoritative feeding style is optimal.',
    verified: true,
  },
  {
    id: 'savage-2007-parental-influence',
    authors: 'Savage JS, Fisher JO, Birch LL',
    year: 2007,
    title: 'Parental Influence on Eating Behavior: Conception to Adolescence',
    source: 'Journal of Law, Medicine & Ethics',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1111/j.1748-720X.2007.00111.x',
    pmid: '17341215',
    volume: '35',
    issue: '1',
    pages: '22-34',
    region: 'global',
    keyFinding: 'Comprehensive review: parental food preferences, availability, accessibility, and feeding styles shape child eating from birth through adolescence.',
    verified: true,
  },
  // 8-12yr: Family meals & independence
  {
    id: 'neumark-sztainer-2010-family-meals',
    authors: 'Neumark-Sztainer D, Wall M, Story M, Fulkerson JA',
    year: 2010,
    title: 'Are Family Meal Patterns Associated with Disordered Eating Behaviors Among Adolescents?',
    source: 'Archives of Pediatrics & Adolescent Medicine',
    type: 'cohort',
    grade: '2b',
    pmid: '20439793',
    volume: '164',
    issue: '5',
    pages: '433-439',
    region: 'global',
    keyFinding: 'Regular family meals associated with lower rates of disordered eating, higher fruit/vegetable intake, and better psychosocial outcomes in adolescents.',
    verified: true,
  },
  {
    id: 'loth-2014-parenting-weight',
    authors: 'Loth KA, MacLehose RF, Fulkerson JA, Crow S, Neumark-Sztainer D',
    year: 2014,
    title: 'Food-Related Parenting Practices and Adolescent Weight Status',
    source: 'Pediatrics',
    type: 'cohort',
    grade: '2b',
    doi: '10.1542/peds.2013-3377',
    pmid: '24733879',
    volume: '133',
    issue: '5',
    pages: 'e1344',
    region: 'global',
    keyFinding: 'Authoritative food parenting (high warmth + structure) associated with healthiest weight outcomes in adolescents.',
    verified: true,
  },
  // 12-15yr: Eating disorders
  {
    id: 'golden-2003-eating-disorders-adolescents',
    authors: 'Golden NH, Katzman DK, Kreipe RE, et al.',
    year: 2003,
    title: 'Eating Disorders in Adolescents: Position Paper of the Society for Adolescent Medicine',
    source: 'Journal of Adolescent Health',
    type: 'consensus',
    grade: '4',
    doi: '10.1016/j.jadohealth.2003.08.004',
    pmid: '14642712',
    volume: '33',
    issue: '6',
    pages: '496-503',
    region: 'global',
    keyFinding: 'Early identification of eating disorders is critical. Pediatricians should screen at well-visits. Includes diagnostic criteria and management framework.',
    verified: true,
  },
  {
    id: 'stice-2011-binge-eating-risk',
    authors: 'Stice E, Marti CN, Rohde P',
    year: 2011,
    title: 'Prevalence, Incidence, Impairment, and Course of the Proposed DSM-5 Eating Disorder Diagnoses in an 8-Year Prospective Community Study',
    source: 'Journal of Abnormal Psychology',
    type: 'cohort',
    grade: '2b',
    doi: '10.1037/a0025578',
    pmid: '22004113',
    volume: '120',
    issue: '1',
    pages: '166-175',
    region: 'global',
    keyFinding: 'Eating disorders affect up to 13% of young women by age 20. Psychological risk factors for onset include body dissatisfaction and dieting.',
    verified: true,
  },
  // 15-18yr: Nutrition literacy
  {
    id: 'larson-2012-food-preparation',
    authors: 'Larson NI, Perry CL, Story M, Neumark-Sztainer D',
    year: 2006,
    title: 'Food Preparation by Young Adults Is Associated with Better Diet Quality',
    source: 'Journal of the American Dietetic Association',
    type: 'cohort',
    grade: '2b',
    doi: '10.1016/j.jada.2005.10.011',
    pmid: '16443415',
    volume: '106',
    issue: '2',
    pages: '211-218',
    region: 'global',
    keyFinding: 'Young adults who prepare food have better diet quality — more fruits, vegetables, whole grains, and less fast food.',
    verified: true,
  },
  {
    id: 'neumark-sztainer-2005-obesity-ed-prevention',
    authors: 'Neumark-Sztainer D',
    year: 2005,
    title: 'Can We Simultaneously Work Toward Prevention of Obesity and Eating Disorders in Children and Adolescents?',
    source: 'International Journal of Eating Disorders',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1002/eat.20181',
    pmid: '16211631',
    volume: '38',
    issue: '3',
    pages: '220-227',
    region: 'global',
    keyFinding: 'Yes — focus on healthy eating behaviors (not weight), body acceptance, family meals, and avoiding unhealthy weight control practices.',
    verified: true,
  },
]

// ════════════════════════════════════════════════════════════════════════════
// PHYSICAL ACTIVITY — 10 tracks, 0-18yr
// ════════════════════════════════════════════════════════════════════════════

const PHYSICAL_ONLY_CITATIONS: Citation[] = [
  // 0-3mo: Tummy time
  {
    id: 'kuo-2008-tummy-time',
    authors: 'Kuo YL, Liao HF, Chen PC, Hsieh WS, Hwang AW',
    year: 2008,
    title: 'The Influence of Wakeful Prone Positioning on Motor Development During the Early Life',
    source: 'Pediatric Physical Therapy',
    type: 'cohort',
    grade: '2b',
    doi: '10.1097/PEP.0b013e31815f108e',
    pmid: '18300929',
    volume: '20',
    issue: '1',
    pages: '11-17',
    region: 'global',
    keyFinding: 'Early tummy time (prone positioning) accelerates head/neck/trunk control and subsequent motor milestones.',
    verified: true,
  },
  {
    id: 'who-2006-motor-development',
    authors: 'WHO Multicentre Growth Reference Study Group',
    year: 2006,
    title: 'WHO Motor Development Study: Windows of Achievement for Six Gross Motor Development Milestones',
    source: 'Acta Paediatrica Supplement',
    type: 'cohort',
    grade: '2a',
    pmid: '16817681',
    volume: '450',
    pages: '86-95',
    region: 'global',
    keyFinding: 'Established normative windows for 6 milestones: sitting without support (3.8-9.2mo), standing with assistance (4.8-11.4mo), walking with assistance (5.9-13.7mo), standing alone (6.9-16.9mo), walking alone (8.2-17.6mo).',
    verified: true,
  },
  // 3-6mo: Rolling & reaching
  {
    id: 'majnemer-2005-supine-motor',
    authors: 'Majnemer A, Barr RG',
    year: 2005,
    title: 'Influence of Supine Sleep Positioning on Early Motor Milestone Acquisition',
    source: 'Developmental Medicine and Child Neurology',
    type: 'cohort',
    grade: '2b',
    doi: '10.1017/S0012162205000733',
    pmid: '15934484',
    volume: '47',
    issue: '6',
    pages: '370-376',
    region: 'global',
    keyFinding: 'Supine sleepers achieve prone milestones (rolling, crawling) slightly later but catch up by 18 months. No long-term motor impact.',
    verified: true,
  },
  {
    id: 'aap-2011-importance-of-play',
    authors: 'Ginsburg KR; Committee on Communications; Committee on Psychosocial Aspects of Child and Family Health',
    year: 2007,
    title: 'The Importance of Play in Promoting Healthy Child Development and Maintaining Strong Parent-Child Bonds',
    source: 'Pediatrics',
    type: 'guideline',
    grade: '4',
    doi: '10.1542/peds.2006-2697',
    pmid: '17200287',
    volume: '119',
    issue: '1',
    pages: '182-191',
    guidelineBody: 'AAP',
    region: 'usa',
    keyFinding: 'Unstructured play is essential for brain development, creativity, and social skills. Overscheduling children reduces free play time.',
    verified: true,
  },
  // 2-3yr: Running, climbing, balls
  {
    id: 'burdette-2005-free-play',
    authors: 'Burdette HL, Whitaker RC',
    year: 2005,
    title: 'Resurrecting Free Play in Young Children: Looking Beyond Fitness and Fatness to Attention, Affiliation, and Affect',
    source: 'Archives of Pediatrics & Adolescent Medicine',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1001/archpedi.159.1.46',
    pmid: '15630057',
    volume: '159',
    issue: '1',
    pages: '46-50',
    region: 'global',
    keyFinding: 'Free play promotes attention, affiliation, and emotional regulation beyond physical fitness. Critical for ages 2-5.',
    verified: true,
  },
  // 3-5yr: Fundamental movement
  {
    id: 'becker-2014-pa-self-regulation',
    authors: 'Becker DR, McClelland MM, Loprinzi P, Trost SG',
    year: 2014,
    title: 'Physical Activity, Self-Regulation, and Early Academic Achievement in Preschool Children',
    source: 'Early Education and Development',
    type: 'cohort',
    grade: '2b',
    doi: '10.1080/10409289.2013.780505',
    volume: '25',
    issue: '1',
    pages: '56-70',
    region: 'global',
    keyFinding: 'Vigorous physical activity in preschoolers predicts better self-regulation and academic achievement. Movement and cognition are linked.',
    verified: true,
  },
  // 5-8yr: Sport exploration
  {
    id: 'cote-2014-sport-participation-model',
    authors: 'Cote J, Vierimaa M',
    year: 2014,
    title: 'The Developmental Model of Sport Participation: 15 Years After Its First Conceptualization',
    source: 'Science and Sports',
    type: 'cohort_review',
    grade: '2a',
    doi: '10.1016/j.scispo.2013.01.012',
    volume: '29',
    pages: 'S63-S69',
    region: 'global',
    keyFinding: 'Sampling years (ages 6-12): try many sports. Specialization too early leads to burnout and dropout. Diversification leads to elite performance.',
    verified: true,
  },
  {
    id: 'barnett-2008-motor-skill-adolescent-pa',
    authors: 'Barnett LM, van Beurden E, Morgan PJ, Brooks LO, Beard JR',
    year: 2008,
    title: 'Childhood Motor Skill Proficiency as a Predictor of Adolescent Physical Activity',
    source: 'Journal of Adolescent Health',
    type: 'cohort',
    grade: '2b',
    doi: '10.1016/j.jadohealth.2007.09.026',
    pmid: '18207090',
    volume: '42',
    issue: '2',
    pages: '130-138',
    region: 'global',
    keyFinding: 'Children with better fundamental motor skills at age 10 are more physically active at age 16. Motor competence predicts lifelong activity.',
    verified: true,
  },
  // 8-12yr: Structured fitness
  {
    id: 'who-2020-pa-sedentary',
    authors: 'World Health Organization',
    year: 2020,
    title: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
    source: 'World Health Organization, Geneva',
    type: 'guideline',
    grade: '4',
    isbn: '9789240015128',
    guidelineBody: 'WHO',
    region: 'global',
    keyFinding: 'Children 5-17yr: at least 60 min/day moderate-to-vigorous PA. Vigorous intensity 3 days/week. Muscle/bone strengthening 3 days/week.',
    verified: true,
  },
  {
    id: 'telama-2005-pa-tracking',
    authors: 'Telama R, Yang X, Viikari J, Valimaki I, Wanne O, Raitakari O',
    year: 2005,
    title: 'Physical Activity from Childhood to Adulthood: A 21-Year Tracking Study',
    source: 'American Journal of Preventive Medicine',
    type: 'cohort',
    grade: '2b',
    doi: '10.1016/j.amepre.2004.12.003',
    pmid: '15766614',
    volume: '28',
    issue: '3',
    pages: '267-273',
    region: 'global',
    keyFinding: '21-year Finnish cohort: physical activity in childhood/adolescence moderately predicts adult activity. Active 9-year-olds are 2-3x more likely to be active adults.',
    verified: true,
  },
  {
    id: 'lloyd-2015-ltad-model',
    authors: 'Lloyd RS, Oliver JL, Faigenbaum AD, et al.',
    year: 2015,
    title: 'Long-Term Athletic Development — Part 1: A Pathway for All Youth',
    source: 'Journal of Strength and Conditioning Research',
    type: 'consensus',
    grade: '4',
    doi: '10.1519/JSC.0000000000000756',
    pmid: '25486295',
    volume: '29',
    issue: '5',
    pages: '1439-1450',
    region: 'global',
    keyFinding: 'Evidence-based LTAD model: movement literacy → sport sampling → specialization. Against early specialization for most sports.',
    verified: true,
  },
  // 12-15yr: Sport specialization debate
  {
    id: 'brenner-2016-sports-specialization',
    authors: 'Brenner JS; AAP Council on Sports Medicine and Fitness',
    year: 2016,
    title: 'Sports Specialization and Intensive Training in Young Athletes',
    source: 'Pediatrics',
    type: 'guideline',
    grade: '4',
    doi: '10.1542/peds.2016-2148',
    pmid: '27550979',
    volume: '138',
    issue: '3',
    guidelineBody: 'AAP',
    region: 'usa',
    keyFinding: 'Early sport specialization increases injury risk (overuse), burnout, and dropout. Delay specialization until late adolescence for most sports.',
    verified: true,
  },
  {
    id: 'gould-2009-athletic-burnout',
    authors: 'Gould D, Whitley MA',
    year: 2009,
    title: 'Sources and Consequences of Athletic Burnout Among College Athletes',
    source: 'Journal of Intercollegiate Sport',
    type: 'cohort',
    grade: '2b',
    volume: '2',
    issue: '2',
    pages: '245-262',
    region: 'global',
    keyFinding: 'Athletic burnout driven by overtraining, pressure from adults, lack of autonomy, and early specialization. Prevention: diversification and athlete-centered coaching.',
    verified: false,
  },
  // 15-18yr: Lifelong fitness
  {
    id: 'eime-2013-sport-psychosocial',
    authors: 'Eime RM, Young JA, Harvey JT, Charity MJ, Payne WR',
    year: 2013,
    title: 'A Systematic Review of the Psychological and Social Benefits of Participation in Sport for Children and Adolescents',
    source: 'International Journal of Behavioral Nutrition and Physical Activity',
    type: 'systematic_review',
    grade: '1a',
    doi: '10.1186/1479-5868-10-98',
    pmid: '23945179',
    volume: '10',
    pages: '98',
    region: 'global',
    keyFinding: 'Team sport participation associated with better self-esteem, social skills, and reduced depression/anxiety in youth. Team > individual sports for psychosocial benefit.',
    verified: true,
  },
  {
    id: 'biddle-2011-pa-mental-health',
    authors: 'Biddle SJH, Asare M',
    year: 2011,
    title: 'Physical Activity and Mental Health in Children and Adolescents: A Review of Reviews',
    source: 'British Journal of Sports Medicine',
    type: 'systematic_review',
    grade: '1a',
    doi: '10.1136/bjsports-2011-090185',
    pmid: '21807669',
    volume: '45',
    issue: '11',
    pages: '886-895',
    region: 'global',
    keyFinding: 'Review of reviews: physical activity has beneficial effects on depression, anxiety, self-esteem, and cognitive function in youth. Evidence strongest for depression.',
    verified: true,
  },
  {
    id: 'biddle-2019-screen-mental-health',
    authors: 'Biddle SJH, Ciaccioni S, Thomas G, Vergeer I',
    year: 2019,
    title: 'Physical Activity and Mental Health in Children and Adolescents: An Updated Review of Reviews and an Analysis of Causality',
    source: 'Current Opinion in Psychiatry',
    type: 'systematic_review',
    grade: '1a',
    doi: '10.1097/YCO.0000000000000492',
    pmid: '30730322',
    volume: '32',
    issue: '4',
    pages: '299-304',
    region: 'global',
    keyFinding: 'Updated review confirms PA benefits for mental health. Screen time associated with poorer mental health but causality unclear.',
    verified: true,
  },
]

// ════════════════════════════════════════════════════════════════════════════
// COMBINED EXPORTS
// ════════════════════════════════════════════════════════════════════════════

export const NUTRITION_GROWTH_CITATIONS: Citation[] = [
  ...SHARED_CITATIONS,
  ...NUTRITION_ONLY_CITATIONS,
]

export const PHYSICAL_GROWTH_CITATIONS: Citation[] = [
  ...SHARED_CITATIONS,
  ...PHYSICAL_ONLY_CITATIONS,
]

export const ALL_NUTRITION_PHYSICAL_CITATIONS: Citation[] = [
  ...SHARED_CITATIONS,
  ...NUTRITION_ONLY_CITATIONS,
  ...PHYSICAL_ONLY_CITATIONS,
]

/** Lookup citation by ID */
export function getNutritionPhysicalCitation(id: string): Citation | undefined {
  return ALL_NUTRITION_PHYSICAL_CITATIONS.find(c => c.id === id)
}

/** Get all citations for a specific domain */
export function getCitationsForNutritionPhysicalDomain(domain: 'nutrition' | 'physical'): Citation[] {
  return domain === 'nutrition' ? NUTRITION_GROWTH_CITATIONS : PHYSICAL_GROWTH_CITATIONS
}

/** Get all verified citations */
export function getVerifiedNutritionPhysicalCitations(): Citation[] {
  return ALL_NUTRITION_PHYSICAL_CITATIONS.filter(c => c.verified)
}

/** Audit summary */
export function getNutritionPhysicalCitationAudit() {
  const all = ALL_NUTRITION_PHYSICAL_CITATIONS
  const verified = all.filter(c => c.verified).length
  const withDoi = all.filter(c => c.doi).length
  const withPmid = all.filter(c => c.pmid).length
  const gradeDistribution = all.reduce((acc, c) => {
    acc[c.grade] = (acc[c.grade] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  return {
    total: all.length,
    verified,
    unverified: all.length - verified,
    withDoi,
    withPmid,
    gradeDistribution,
    verificationRate: `${Math.round((verified / all.length) * 100)}%`,
    domains: {
      nutrition: NUTRITION_GROWTH_CITATIONS.length,
      physical: PHYSICAL_GROWTH_CITATIONS.length,
      shared: SHARED_CITATIONS.length,
    },
  }
}
